Welcome: Welcome
Unknown: Unknown
Yes: Yes
No: No
Save: Save
Name: Name
Information: Information
View: View
Edit: Edit
Close: Close
Email: Email
Password: Password
PasswordAgain: Password again
IsVerified: Is verified
IsAdmin: Is admin
Admin: Admin
ActionNotImplemented: Action is not implemented
Revoke: Revoke
Permit: Permit
AddPermission: Add permission
NewPassword: New password
Remove: Remove
Id: Id
Logout: Logout
Login: Login
Write: Write
Preview: Preview

Home: Home

NewUser: New user
User: User
Users: Users
NoUsers: No users found
EditUser: Edit user
UserCreated: New user was created
CreateUser: Create new user
UserUpdated: User updated
Confirm: Confirm
PasswordsDidntMatch: Passwords didin't match
PasswordTwice: You must enter the password twice
RemoveUser: Remove user
AreYouSure: Are you sure?
SureRemoveUser email@Text: Are you sure you want to remove user #{email}?
CantDeleteRoot: Can't delete the root user
UserRemoved: User removed
ViewUser: View user

Pages: Pages
NoPages: No pages found
Page: Page
EditPage: Edit page
IsPublic: Is public
Body: Body
CreatePage: Create page
NewPage: New page
PageUpdated: Page updated
PageCreated: Page created
RemovePage: Remove page
SureRemovePage name@Text: Are you sure you want to remove page #{name}?
CantRemoveFirstPage: Can't remove the first page
PageRemoved: Page removed
ViewPage: View page
Permalink: Permalink
