Welcome: Welcome
Unknown: Unknown
Yes: Yes
No: No
Save: Save
Name: Name
Information: Information
View: View
Edit: Edit
Close: Close
Email: Email
Password: Password
PasswordAgain: Password again
IsVerified: Is verified
IsAdmin: Is admin
Admin: Admin
ActionNotImplemented: Action is not implemented
Revoke: Revoke
Permit: Permit
AddPermission: Add permission
NewPassword: New password
Remove: Remove
Id: Id
Logout: Logout
Login: Login
Write: Write
Preview: Preview

Home: Home

NewUser: New user
User: User
Users: Users
NoUsers: No users found
EditUser: Edit user
UserCreated: New user was created
CreateUser: Create user
UserUpdated: User updated
Confirm: Confirm
PasswordsDidntMatch: Passwords didin't match
PasswordTwice: You must enter the password twice
RemoveUser: Remove user
AreYouSure: Are you sure?
SureRemoveUser email@Text: Are you sure you want to remove user #{email}?
CantDeleteRoot: Can't delete the root user
UserRemoved: User removed
ViewUser: View user

Pages: Pages
NoPages: No pages found
Page: Page
EditPage: Edit page
IsPublic: Is public
Body: Body
CreatePage: Create page
NewPage: New page
PageUpdated: Page updated
PageCreated: Page created
RemovePage: Remove page
SureRemovePage name@Text: Are you sure you want to remove page #{name}?
CantRemoveFirstPage: Can't remove the first page
PageRemoved: Page removed
ViewPage: View page
Permalink: Permalink
PageSlugExists slug@Text: Page with slug "#{slug}" exists already
Previous: Previous
Next: Next

Theme: Theme
ExistingExports: Existing exports
RenamedExports: Renamed exports
RemovedExports: Removed exports
VersionIntroduced: Introduced in version
VersionRenamed: Renamed in version
VersionRemoved: Removed in version
NewName: New name
APIReference: API Reference
CompabilityCheck: Compability check

SetPass: Set a new password
SetPassTitle: Set password
CurrentPassword: Current password
NewPass: New password
ConfirmPass: Confirm

PasswordResetTitle: Password Reset
PasswordResetPrompt: Enter your e-mail address or username below, and a password reset e-mail will be sent to you.
SendPasswordResetEmail: Send password reset email
RegisterLong: Register a new account
EnterEmail: Enter your e-mail address below, and a confirmation e-mail will be sent to you.
Register: Register


